config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    devise_for :users, controllers: { registrations: 'users/registrations' }
    resources :users do
        resource :profile
    end
    get 'about', to: 'pages#about'
    resources :contacts, only: :create
    get 'contact-us', to: 'contacts#new', as: 'new-contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    #contact form validations
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end
 

app/models/plan.rb
class Plan < ActiveRecord::Base
    
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  has_one :profile

  
  attr_accessor :stripe_card_token 
  # If Pro User passes validations (email, password, etc.)
  # then call stripe and tell it to set up a subscription
  # upon charging the customer's card. 
  # Stripe responds with customer data, and we store 
  # customer.id as the customer token. 
   def save_with_subscription
     if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
     end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Whitelist the following form fields so we can process them if 
  # coming from a Devise sign-up form
  before_action :configure_premitted_parameters, if: :devise_controller?

  protected
    def configure_premitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
    
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    #show new contact form
    def new
        @contact = Contact.new
    end
    
    #POST request / contacts
    def create
        #mass assignment of form fields into contact object
        @contact = Contact.new(contact_params)
        #save contact object to database
        if @contact.save
            #store form fields via parameters into local variables
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            #plug variables into Contact Mailer
            #store success message and flash hash
            #and redirect to the new action
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = "Message sent."
            redirect_to new_contact_path
        else
            #if contact object doesn't save, store
            #errors in flash hash and redirect to new action
            flash[:danger] = @contact.errors.full_messages.join(", ")
            redirect_to new_contact_path
        end
    end
    
    private
        #to collect data from form we need to use
        #strong parameters and whitelist the form fields
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
    end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #Get request for / which is our home page
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  def about
  end
end
    

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    # GET to  /users/:user_id/profile/new
    def new
      # Render blank profile details form
      @profile = Profile.new
    end
    
    # POST to /users/:user_id/profile
    def create
      # ensure we have user who is filling out form
      @user = User.find( params[:user_id] )
      # create profile linked to this specific user
      @profile = @user.build_profile( profile_params )
      if @profile.save
        flash[:success] = "Profile updated!"
        redirect_to root_path
      else
        render action :new
      end
    end
    
    private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :job_title, :phone_number, :contact_email, :description)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :select_plan, only: :new
    
    # Extend default devise gem behavior so that
    # users signing up with Pro account (Plan ID 2)
    # save with a special Stripe subscription function.
    # Otherwise sign up user as usual. 
    def create
      super do |resource|
        if params[:plan]
          resource.plan_id = params[:plan]
          if resource.plan_id == 2
            resource.save_with_subscription
          else
            resource.save 
          end
        end
      end
    end
    
    private 
      def select_plan
        unless (params[:plan] == '1' || params[:plan] == '2')
          flash[:notice] = "Please select a membership plan to sign up."
          redirect_to root_url
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <h3 class="text-center">Contact Us</h3>
        
        <div class="col-md-4 col-md-offset-4">
            <% flash.each do |type, msg| %>
                <% content_tag :div, msg, class: "alert, alert-#{type}" %>
            <% end %>
            <div class= "well">
                <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>  
                
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :comments %>
                    <%= f.text_field :comments, class: 'form-control' %>
                </div>
                
                <%= f.submit 'Submit', class: 'btn btn-default' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700i,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/', type: 'text/javascript' %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name == "stripe-key", :content == STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to root_path, class: "navbar-brand" do %>
        <icon class="fa fa-group"></icon>
          DevMatch
        <% end %>
      </button>
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-default navbar-btn" %>
          <% end %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", about_path %></li> 
          <li><%= link_to "Contact Us", new_contact_path %></li>
        </ul>
      </div>
    </nav>
    
    <div class='flash-container'>
      <% flash.each do |type, msg| %>
        <% content_tag :div, msg, class: "alert, alert-#{type}" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
  <h1>About Page</h1>
  <p> We are DevMatch, we focus on creating an exclusive community for developers and entrepreuners to meet.</p>
</div>

app/views/pages/home.html.erb
<div class= "home-callout text-center container-fluid">
    <h1>Welcome to DevMatch.</h1>
    <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>

<div class ="container home-signup-links">
    <div class="row">
        <div class="col-md-6">
            <div class="well">
                <h2 class="text-center">Basic Membership</h2>
                <h4 class="text-center">Sign up for free and get basic access to the community</h4>
                <br/>
                <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block'%>
            </div>
        </div>
        <div class="col-md-6">
            <div class="well">
                <h2 class="text-center">Pro Membership</h2>
                <h4 class="text-center">Sign up for the pro account for $10/month and get access to community and contact information</h4>
                <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block'%>
            </div>
        </div>
    </div>
    <%= link_to "Create your Profile", new_user_profile_path(user_id: current_user.id) if user_signed_in? %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/new.html.erb
Profile new form goes here